language: r

before_install:
  - sudo apt-get install libudunits2-dev

r:
  - 4.0.2

install:
  - R -e "install.packages('packrat')"
  - R -e "packrat::restore(restart = FALSE)"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

deploy:
  provider: script
  file_glob: true
  script: bash scripts/ci/package.sh
  on:
    branch: develop
